a: Added screen argument.

diff --git a/bin/a b/bin/a
--- a/bin/a
+++ b/bin/a
@@ -2,7 +2,7 @@
 
 usage()
 {
-    echo "usage: ${0##*/} [start|volume|coc] ARGS" 1>&2
+    echo "usage: ${0##*/} [start|volume|coc|screen] ARGS" 1>&2
     exit "$@"
 }
 
@@ -23,11 +23,11 @@ cmd_start()
 
     case "$1" in
     coc)
-        adb shell monkey -p com.supercell.clashofclans -c android.intent.category.LAUNCHER 1
+        $PREFIX monkey -p com.supercell.clashofclans -c android.intent.category.LAUNCHER 1
         exit $?
         ;;
     tunein)
-        adb shell monkey -p radiotime.player -c android.intent.category.LAUNCHER 1
+        $PREFIX monkey -p radiotime.player -c android.intent.category.LAUNCHER 1
         ;;
     -l)
         cat << EOF
@@ -47,8 +47,8 @@ cmd_volume()
     [ $# -ge 1 ] || err "missing volume argument"
 
     case "$1" in
-    up) adb shell input keyevent 24; exit $?  ;;
-    down) adb shell input keyevent 25; exit $?  ;;
+    up) shift; $PREFIX input keyevent "$@" 24; exit $? ;;
+    down) shift; $PREFIX input keyevent "$@" 25; exit $? ;;
     -h)
         echo "usage: ${0##*/} volume [up|down]"
         exit 0
@@ -75,14 +75,43 @@ cmd_coc()
     esac
 }
 
+is_screen_on()
+{
+    $PREFIX dumpsys power | grep -q mScreenOn=true
+}
+
+cmd_screen()
+{
+    [ $# -ge 1 ] || err "missing screen argument"
+
+    case "$1" in
+    on) is_screen_on || $PREFIX input keyevent 26; exit $? ;;
+    off) is_screen_on && $PREFIX input keyevent 26; exit $? ;;
+    -h)
+        echo "usage: ${0##*/} screen [on|off]"
+        exit 0
+        ;;
+    *)
+        err "$1: invalid argument"
+        ;;
+    esac
+}
+
 main()
 {
     [ $# -ge 1 ] || err "missing arguments"
+
+    if [ -f /etc/lsb-release ]; then
+        PREFIX="adb shell"
+    else
+        PREFIX=""
+    fi
 
     case "$1" in
     start) shift; cmd_start "$@" ;;
     volume) shift; cmd_volume "$@" ;;
     coc) shift; cmd_coc "$@" ;;
+    screen) shift; cmd_screen "$@" ;;
     -h) usage 0 2>&1 ;;
     *) warn "$1: invalid argument"; usage 1 ;;
     esac
